### ISSUE TITLE
UPF F-TEID allocation

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#120]
I'm as a UPF vendor can configure UPF to allocate IP addressed for PDU sessions locally.

Acceptance criteria:

- [x] Explore how it works ([5.21.3 UE IP address/prefix allocation in the UP function](https://www.etsi.org/deliver/etsi_ts/129200_129299/129244/16.04.00_60/ts_129244v160400p.pdf))
- [x] Implement IP pool
- [x] Set FTUP flag during PFCP Association Request/Respose
- [x] Use CH flag to trigger TEID allocation
- [x] **Fix incorrect message format error (!)**
- [x] Update README: functional description + 3gpp compatibility
- [x] Add issues to free5gc to support `FTUP`
- [ ] Present to team

3GPP TS 23.501 5.8.2.2 UE IP Address Management 
```
When Static IP addresses for a PDU session are not used, the actual allocation of the IP Address(es) for a PDU Session
may use any of the following mechanisms:
- The SMF allocates the IP address from a pool that corresponds to the PDU Session Anchor (UPF) that has been
selected
- The UE IP address is obtained from the UPF. In that case the SMF shall interact with the UPF via N4 procedures
to obtain a suitable IP address. The SMF provides the UPF with the necessary information allowing the UPF to
derive the proper IP address (e.g. the network instance).
...
A given IP address pool is controlled by a unique entity (either the SMF or the UPF or an external server). The IP
address managed by the UPF can be partitioned into multiple IP address pool partition(s), i.e. associated with multiple
IP address pool ID(s).
When the SMF is configured to obtain UE IP addresses from the UPF, the SMF may select a UPF based upon support
of this feature. The SMF determines whether the UPF supports this feature via NRF or via N4 capability negotiation
during N4 Association Setup. If no appropriate UPF support the feature, the SMF may allocate UE IP addresses, if
configured to do so.
The IP address/prefix is released by the SMF (e.g. upon release of the PDU Session), likewise the UPF considers that
any IP address it has allocated within a N4 session are released when this N4 session is released. 
```

TS 129 244 Table 7.5.2.2-2: PDI IE within PFCP Session Establishment Request
![Image](https://github.com/edgecomllc/eupf/assets/20152142/a299f561-aaed-4b12-bd48-ed6c129f7333)

![Image](https://github.com/edgecomllc/eupf/assets/20152142/399301d5-da50-44fc-8ef4-93bca37da2a8)

**Comment by arxxm** [comment]
free5gc issue: https://github.com/free5gc/free5gc/issues/509
