### ISSUE TITLE
eUPF in Google Cloud Services

### ISSUE THREAD

**Issue by ewdss** [edgecomllc/eupf#193]
- [x] Explore GCP capabilities/features required
- [x] Try to deploy eUPF in Google Cloud Services
- [x] Prepare brief report

**Comment by mbaran0v** [comment]
> can we deploy eUPF to GKE cluster?

yes, kernel version is 5.15

> can we use host network?

yes

> can we use privileged container?

yes

> can we use host nat?

no, GKE not support multus

> ca we use container nat?

no, GKE not support multus?

**Comment by mbaran0v** [comment]
[Разворачивание eUPF в Google Cloud Platform (GCP).docx](https://github.com/edgecomllc/eupf/files/12589504/eUPF.Google.Cloud.Platform.GCP.docx)
