### ISSUE TITLE
Investigate problem with routing to eUPF for outside

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#205]
**WHO**: MNO & supplier
**WHAT**: UPF announces UE routes
**WHY**: UPF deployment announcement automation without crunches

Restrictions:

- BGP on node (Bird in Calico)

Questions:
- What to do if N3 interface is unavailable? Disable route in BGP?
- Where UPF should find UE subnet to annouce? Who manages UE subnet UPF or SMF? If SMF should me manualy configure subnet on UPF or aggregate every IP in meta-subnet before annouce?  

DoD:
- [x] UE-subnet announcement from eUPF pod to K8s (BGP)
- [x] Reflect UE-subnet to outside of the K8s cluster

**Comment by PapaySail** [comment]
ℹ To think about
Amazon [LTE and 5G Data Network Breakout Designs on AWS](https://aws.amazon.com/ru/blogs/industries/lte-and-5g-data-network-breakout-designs-on-aws/)
6 Solution Designs
>There are multiple designs for how LTE or 5G user plane traffic can breakout to the internet or to an application for a non-roaming scenario. AWS offers various services that enable CSP to send SGi or N6 traffic toward an application for both public and private network use cases.
