### ISSUE TITLE
Create separete 5GC and UPF deployments

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#237]
- [x] Deploy UERANSIM, 5GC(Open5GS) and UPF in different clusters
- [ ] Configure proper UERANSIM, 5GC(Open5GS) and UPF interaction
- [x] Run eUPF in host network mode to overcome k8s restriction on external port range (eUPF GTP port should be available to gNB)
- [ ] Standalone UPF deployment configuration prepared as separate configuration option

**Comment by mbaran0v** [comment]
now, we can't implement this task

**Comment by pirog-spb** [comment]
FYI

gNB Configuration (UERANSIM):

- **mcc/mnc**: This fields are already explained above.
- ...
- **gtpAdvertiseIp**: If you want to separate GTP listening address and external access address, you can set this value to override Downlink User-Plane Transport Layer Address which is advertised to UPF. This field is optional and not required for most of the people. It is especially useful in case of a NAT between gNB and UPF. We didn't include this field in the sample config files.

**Comment by mbaran0v** [comment]
can see here https://github.com/edgecomllc/things-for-demo/blob/master/step3/manifests/docker-compose.yaml
scheme https://miro.com/app/board/uXjVPlO58Jc=/?moveToWidget=3458764560658672251&cot=14
