### ISSUE TITLE
Add advertising PFCP and GTP addresses

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#308]
- [x] Advertised PFCP address should be in NODE-ID (may be FQDN in NODE ID would be enough, but local IP address may be required as well)
- [x] Investigate how advertised GTP-U address is sent to SMF in open5gs/free5gc
- [x] Ask Open5gs community why UPF doesn't send `UP resourses bla-bla-bla`
- [ ] Implement sending `UP resourses bla-bla-bla` during association establishment

**Comment by marknefedov** [comment]
Open5GS config:
```
#  o Provide custom PFCP address to be advertised to SMF in PFCP association
#      request/respond
#  upf:
#    pfcp:
#      - addr: 0.0.0.0
#        advertise: open5gs-smf.svc.local

#  o Provide custom UPF GTP-U address to be advertised inside NGAP messages
#  upf:
#    gtpu:
#      - addr: 10.4.128.21
#        advertise: 172.24.15.30
```

PFCP part is probably sent in the NodeId.
GTP theoreticaly somehow passed from UPF to SMF wich is forwarding to gNB.

**Comment by marknefedov** [comment]
NGAP is a protocol between NG-RAN and AMF: https://www.etsi.org/deliver/etsi_ts/138400_138499/138413/15.00.00_60/ts_138413v150000p.pdf

So, it is highly unlikely that UPF pass over info to SMF. Need to investigate Open5GS sources.

**Comment by marknefedov** [comment]
https://github.com/open5gs/open5gs/discussions/2442

**Comment by pirog-spb** [comment]
Advertising UPF's N3 IP will be supported as a result of #466
