### ISSUE TITLE
Apply zero ebpf program automatically

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#309]
eUPF deployment automatically attaches zero ebpf program to host parts of eUPF interfaces when attachment mode for eUPF is native.

Zero ebpf program: `zero_entrypoint_bpf.o` (is built inside eupb (go:generate step))

In order to attach ebpf use `ip` command:
```
sudo ip link set dev vethc20fbaf xdpdrv obj zero_entrypoint_bpf.o sec xdp/upf_zero_entrypoint
```

Acceptance criteria:

- [x] There is a job in deployment with attaches zero-entrypoint for host part of eupf veth interface
- [x] Job works for open5gs
- [x] There is an option in deployment for enable/disable this behaviour
- [ ] Feature documented
- [x] Feature presented to team

**Comment by PapaySail** [comment]
OK fixed k8s job to work properly /
Problem:  link prog/xdp auto detached in a minute at the node level:
```
Timestamp: Tue Sep  5 11:20:10 2023 807582 usec
1589: vethe8e20347@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 xdp/id:33462 qdisc noqueue state UP group default event FEATURE CHANGE
    link/ether ee:ba:88:00:96:86 brd ff:ff:ff:ff:ff:ff link-netns cni-85622858-9a61-1dc9-eac9-f450bca117af
Timestamp: Tue Sep  5 11:20:10 2023 807935 usec
1589: vethe8e20347@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether ee:ba:88:00:96:86 brd ff:ff:ff:ff:ff:ff link-netns cni-85622858-9a61-1dc9-eac9-f450bca117af
```
Possible reason is [CoreDNS](https://coredns.io/explugins/ebpf/):
> When CoreDNS exits, the program will be detached from the interface.

Further research direction is [bpfd](https://bpfd.dev/).
> bpfd is a system daemon aimed at simplifying the deployment and management of eBPF programs.
bpfd includes a Kubernetes operator to bring those same features to Kubernetes, allowing users to safely deploy eBPF via custom resources across nodes in a cluster.
