### ISSUE TITLE
Review deployment architecture according to cloud restrictions

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#313]
- [ ] Research how to deploy eUPF without Multus 
- [ ] Research how to deploy free5gc without Multus
- [ ] Decide what to do with kernel version (eUPF needs >= 5.7) required for ebpf support
- [x] Verify all required node-level configuration options
- [x] Call to external expertize (post to relevant platform, any examples of deployed 5GC in K8s, routing to internal IPs without NAT/internal IPs announcement)

https://github.com/m4r1k/k8s_5g_lab

**Comment by ewdss** [comment]
Our reddit thread:
https://www.reddit.com/r/kubernetes/comments/14g7w41/question_about_networking_in_kubernetes_cluster/

**Comment by mbaran0v** [comment]
>> Research how to deploy eUPF without Multus

2 options:
- use host network
- use BGP peering between calico and external router

>> Research how to deploy free5gc without Multus

i could not find alternative charts for free5gs, but we can use our universal chart for try to deploy it

>> Decide what to do with kernel version (eUPF needs >= 5.7) required for ebpf support

??

>> Verify all required node-level configuration options

for host nat, we need host network, and sysctl forwarding options
