### ISSUE TITLE
Slicing options research

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#314]
Network slicing is one of the core featuers that is relevant for our potential customers in the 5G networks. We are going to conduct some trials in a live environment (5G Base Stations, 5G control plane core). But we should have some "light' demo options to conduct "virtual" demo of the eUPF with the OpenSouce UE, gNB and Core. 

The goal of this issue is to research EURANSIM and Open5GS/Free5GC features for the network slicing. 

- [x] EURANSIM is ready for slicing OR what amount of development is required to make it ready?
- [x] Open5GS is ready for slicing OR what amount of development is required to make it ready?
- [x] Free5GC is ready for slicing OR what amount of development is required to make it ready?
- [x] Research slicing options/alternatives
- [x] Define what actions should be done to configure/activate slicing inside gNB and Core
- [x] Define what actions should be done to activate slice on a virtual UE from UERANSIM bundle. 
- [ ] Describe possible slicing demo scenarios in a virtual environment.

**Comment by marknefedov** [comment]
https://forum.free5gc.org/t/is-network-slicing-function-working-on-free5gc-stage3/162/4

https://github.com/open5gs/open5gs/issues/821

**Comment by pirog-spb** [comment]
![Image](https://github.com/edgecomllc/eupf/assets/20152142/3b314c89-1d72-453d-8481-9087ee8a311d)

https://www.techplayon.com/5g-ran-and-5gc-network-slice-signaling/

**Comment by pirog-spb** [comment]
Open5GS - slicing compatible.
See a bunch of articles for detailes: https://github.com/s5uishida/open5gs_5gc_ueransim_sample_config

**Comment by pirog-spb** [comment]
Free5GC - slicing compatible.
https://github.com/s5uishida/free5gc_ueransim_snssai_upf_sample_config
