### ISSUE TITLE
Investigate UERANSIM GTP-U port issue

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#315]
It is not possible to configure 1251 GTP port of UPF to outer world in K8s.

- [x] Chech UERANSIM issues list
- [ ] Ask UERANSIM contributors
- [x] Check Free5GC/Open5GS related issues
- [ ] Hotfix UERANSIM gtp-u port (use config value for example)
- [ ] Propose PR for UERANSIM

#237

**Comment by PapaySail** [comment]
### Idea is to utilize an Egress Router Pod + Service
https://stackoverflow.com/a/75967660
> One viable solution is to utilize an Egress Router resource defined [here](https://docs.openshift.com/container-platform/4.12/networking/openshift_sdn/using-an-egress-router.html), which redirects traffic to a specified IP
For more information on implementing the egress router in redirection mode, see [here](https://docs.openshift.com/container-platform/4.12/networking/openshift_sdn/deploying-egress-router-layer3-redirection.html#deploying-egress-router-layer3-redirection).

image: registry.redhat.io/openshift4/ose-egress-router
[Egress destination configuration format](https://docs.openshift.com/container-platform/4.12/networking/openshift_sdn/deploying-egress-router-layer3-redirection.html#nw-egress-router-dest-var_deploying-egress-router-layer3-redirection)
> <port> <protocol> <ip_address> <remote_port> - As above, except that the connection is redirected to a different <remote_port> on <ip_address>.
Example configuration
    `8080 tcp 203.0.113.26 80`
    `8443 tcp 203.0.113.26 443`
redirect local ports 8080 and 8443 to remote ports 80 and 443 on 203.0.113.26.

**Comment by PapaySail** [comment]
device "macvlan0" is needed inside a router Pod

**Comment by PapaySail** [comment]
### Chech UERANSIM issues list
Search queries viewed:
- https://github.com/aligungr/UERANSIM/issues?q=is%3Aissue+UPF+port+
- https://github.com/aligungr/UERANSIM/issues?q=is%3Aissue+GTP+port
- https://github.com/aligungr/UERANSIM/issues?q=is%3Aissue+2152

https://github.com/aligungr/UERANSIM/wiki/Configuration#environment
>SCTP protocol with default port number 38412 is used between gNB and AMF. GTP protocol with assigned port number 2152 is used between gNB and UPF. RLS protocol with assigned port number 4997 is used between gNB and UE.

Repo search : constant `GtpPort = 2152` for listening and sending UDP gtpPdu.
- https://github.com/search?q=repo%3Aaligungr%2FUERANSIM%20gtpPort&type=code
  - https://github.com/aligungr/UERANSIM/blob/3a96298fa284b0da261a60439b21c1adf1677aea/src/utils/constants.hpp#L25
  `static constexpr const uint16_t GtpPort = 2152;`
- https://github.com/aligungr/UERANSIM/blob/3a96298fa284b0da261a60439b21c1adf1677aea/src/gnb/gtp/task.cpp#L218
  `            m_udpServer->send(InetAddress(pduSession->upTunnel.address, cons::GtpPort), gtpPdu);`

---
📝 OpenAirInterface [OAI-5G Core Network (CN)](https://openairinterface.org/oai-5g-core-network-project/) project group is to provide a 3GPP-Compliant 5G Standalone (SA) CN implementation
> deployment modes: 
> 3) [Slicing 5GC](https://gitlab.eurecom.fr/oai/cn5g/oai-cn5g-fed/-/blob/master/docs/DEPLOY_SA5G_SLICING.md) with AMF, SMF, NRF, UPF, UDM, AUSF, UDR, and NSSF
UPF flavors: 
>2) [VPP-UPF](https://gitlab.eurecom.fr/oai/cn5g/oai-cn5g-upf-vpp.git) (relying on VPP-Travelping, with DPDK support)
>3) Production grade UPF (SD-Fabric, on-going)
Three deployment platforms: 
>1) Bare-metal installation or in virtual machines
>2) Automated deployment of NFs in Docker containers using Docker-Compose
>3) Cloud-native deployment using Helm Chart (on OpenShift/Kubernetes cluster)

- Docker-compose: [OpenAirInterface 5G Core Network Deployment and Testing with UERANSIM](https://gitlab.eurecom.fr/oai/cn5g/oai-cn5g-fed/-/blob/master/docs/DEPLOY_SA5G_WITH_UERANSIM.md)
- [oai-5gc & UERANSIM Docker Compose](https://bitbucket.org/infinitydon/oai-5g-docker-compose/src/main/)

**Comment by PapaySail** [comment]
### Check Free5GC/Open5GS related issues
Search queries viewed:
- https://github.com/free5gc/free5gc/issues?q=is%3Aissue+2152
- https://github.com/open5gs/open5gs/issues?q=is%3Aissue+2152
There is no related info.

**Comment by PapaySail** [comment]
To use [UDP port forwarding with socat](https://mattryall.net/blog/udp-port-forwarding-with-socat)
> `sudo socat UDP4-RECVFROM:161,fork UDP4-SENDTO:localhost:10161`

or `socat -T 600 UDP4-LISTEN:5353,reuseaddr,fork UDP4:114.114.114.114:53`
http://www.dest-unreach.org/socat/

https://hub.docker.com/r/alpine/socat
here is another example: [socat on Kubernetes - From pet to cattle](https://pet2cattle.com/2021/07/expose-localhost-using-socat)

**Comment by PapaySail** [comment]
### Another method - use iptables to configure port forwarding in Linux
inside GnB Pod like this:
```powershell
sudo iptables -A INPUT -p udp --dport {port_number} -j ACCEPT

sudo iptables -t nat -A PREROUTING -p udp --dport {port_number} -j DNAT --to-destination {destination_ip_address}:{destination_port_number}
```
