### ISSUE TITLE
Create test plan

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#316]
- [x] Define what we want to focus on
- [x] Create & prioritize test cases list
- [x] Define how we will test (instruments, frameworks, etc)

**Comment by ewdss** [comment]
[Software Testing - Base Course (Svyatoslav Kulikov) - 3rd edition - RU.pdf](https://github.com/edgecomllc/eupf/files/11802238/Software.Testing.-.Base.Course.Svyatoslav.Kulikov.-.3rd.edition.-.RU.pdf)

**Comment by marknefedov** [comment]
## **Unit Test Cases (can be done in Go)**

1. eBPF map key validation
    - Test reads.
    - Test writes.
2. Test intermediate interfaces (**ELABRORATE**)
    - Test correct data flow between interfaces.
    - Test error handling for invalid data.
3. Test sessions CRUD
4. PFCP Message parsing/converting to internal structures.
    - Test correct parsing of PFCP messages.
    - Test conversion of PFCP messages to internal data structures.
5. XDP Tests
    - Test XDP program loading and unloading.
    - Test XDP program functionality with valid and invalid packets.

## **Integration Test Cases (can be done in Go)**

1. Test proper PFCP message handling.
    - Test correct response generation.
    - Test eBPF maps updated to expected values.
    - Test associations/sessions updated to expected values.
2. Test error handling for invalid PFCP messages.
    - Test response generation for invalid messages.
    - Test eBPF maps and associations/sessions remain unchanged.
3. Test multiple sessions.

## **End-to-End Test Cases (needs external tools, manual testing)**

1. Run scenario 0 with free5gc/open5gs.
    - Test successful connection and communication with free5gc/open5gs
    - Test correct handling of different network scenarios
2. Test performance and scalability
    - Test the UPF's ability to handle a large number of sessions and associations.
    - Test the UPF's ability to maintain performance under high traffic loads.

<aside>
💡 It appears to be possible to write a test harness to run commands and validate output using https://github.com/kubernetes/client-go.

</aside>

## **Negative Test Cases**

1. Unit Test Cases
    - Test eBPF map key validation with invalid keys
    - Test intermediate interfaces with invalid data
    - Test PFCP message parsing with malformed messages
2. Integration Test Cases
    - Test PFCP message handling with invalid or incomplete messages
    - Test associations/sessions updates with conflicting or invalid data
3. End-to-End Test Cases
    - Test UPF's behavior when external tools (free5gc/open5gs) are unavailable or unresponsive.
    - Test UPF's behavior under extreme network conditions (high latency, packet loss, etc.)

## Other

Fuzzing [[Go Fuzzing - The Go Programming Language](https://go.dev/security/fuzz/)](https://go.dev/security/fuzz/)

[[scapy.contrib.pfcp — Scapy 2.5.0 documentation](https://scapy.readthedocs.io/en/latest/api/scapy.contrib.pfcp.html)](https://scapy.readthedocs.io/en/latest/api/scapy.contrib.pfcp.html)

[[Code Coverage in Golang - Golang Docs](https://golangdocs.com/code-coverage-in-golang)](https://golangdocs.com/code-coverage-in-golang)

[[kube - Rust (docs.rs)](https://docs.rs/kube/latest/kube/index.html)](https://docs.rs/kube/latest/kube/index.html)

**Comment by marknefedov** [comment]
# Tests:

## eBPF Map Key Validation Test

- **Test objective**: Test that the eBPF map can properly handle valid and invalid keys.
- **Test execution**: Attempt to read and write to the eBPF map using the valid and invalid keys.
- **Test assertions**: Verify that reading and writing to the eBPF map with valid keys succeeds, and that reading and writing to the eBPF map with invalid keys fails.

## Sessions CRUD Test

- **Test objective**: Test the creation, read, update, and deletion of sessions.
- **Test execution**: Attempt to read, update, and delete the session.
- **Test assertions**: Verify that the session can be read, updated, and deleted.

## PFCP Message Parsing Test

- **Test objective**: Test the correct parsing of PFCP messages.
- **Test setup**: Create a PFCP message and populate it with data.
- **Test execution**: Parse the PFCP message and convert it to internal data structures.
- **Test assertions**: Verify that the PFCP message is properly parsed and converted to internal data structures.

## XDP Tests

- **Test objective**: Test the loading and unloading of XDP programs and their functionality with valid and invalid packets.
- **Test execution**: Load the XDP program and send valid and invalid packets through it.
- **Test assertions**: Verify that the XDP program is properly loaded and that valid packets are properly processed while invalid packets are dropped.
- **Test teardown**: Unload the XDP program.

## Proper PFCP Message Handling Test

- **Test objective**: Test the proper handling of PFCP messages, including correct response generation, eBPF maps updated to expected values, and associations/sessions updated to expected values.
- **Test setup**: Create a PFCP message and populate it with data.
- **Test execution**: Send the PFCP message to the UPF and verify that the response is correct, eBPF maps are updated to expected values, and associations/sessions are updated to expected values.
- **Test assertions**: Verify that the response is correct, eBPF maps are updated to expected values, and associations/sessions are updated to expected values.

## Invalid PFCP Messages Error Handling Test

- **Test objective**: Test the error handling for invalid PFCP messages, including response generation for invalid messages and eBPF maps and associations/sessions remaining unchanged.
- **Test setup**: Create an invalid PFCP message.
- **Test execution**: Send the invalid PFCP message to the UPF and verify that the response is correct and eBPF maps and associations/sessions remain unchanged.
- **Test assertions**: Verify that the response is correct and eBPF maps and associations/sessions remain unchanged.

## Multiple Sessions Test

- **Test objective**: Test the ability of the UPF to handle multiple sessions.
- **Test setup**: Create multiple sessions via SessionEstablishRequest message and populate them with data.
- **Test execution**: Attempt to read, update, and delete the sessions.
- **Test assertions**: Verify that the sessions can be read, updated, and deleted.
- **Test teardown**: Delete the sessions.

## Scenario 0 Test

- **Test objective**: Test the successful connection and communication with free5gc/open5gs, and correct handling of different network scenarios.
- **Test setup**: Set up free5gc/open5gs and the UPF.
- **Test execution**: Attempt to connect and communicate with free5gc/open5gs
- **Test assertions**: Verify successful connection and communication with free5gc/open5gs and correct handling of different network scenarios.
- **Test teardown**: Delete free5gc/open5gs and the UPF.

## Performance and Scalability Test*

- **Test objective**: Test the ability of the UPF to handle a large number of sessions and associations and maintain performance under high traffic loads.
- **Test setup**: Create a large number of sessions and associations and generate high traffic loads.
- **Test execution**: Attempt to handle the large number of sessions and associations and maintain performance under high traffic loads.
- **Test assertions**: Verify that the UPF can handle the large number of sessions and associations and maintain performance under high traffic loads.
- **Test teardown**: Delete the large number of sessions and associations.

## PFCP Message Parsing Negative Test

- **Test objective**: Test that PFCP message parsing fails with malformed messages.
- **Test setup**: Create a malformed PFCP message.
- **Test execution**: Parse the malformed PFCP message and attempt to convert it to internal data structures.
- **Test assertions**: Verify that the malformed PFCP message fails to parse and convert to internal data structures.

## PFCP Message Handling Negative Test

- **Test objective**: Test that PFCP message handling fails with invalid or incomplete messages.
- **Test setup**: Create an invalid or incomplete PFCP message.
- **Test execution**: Send the invalid or incomplete PFCP message to the UPF
- **Test assertions**: Verify that the response is incorrect and eBPF maps and associations/sessions remain unchanged.
- **Test teardown**: Delete the invalid or incomplete PFCP message.

## Associations/Sessions Updates Negative Test

- **Test objective**: Test that associations/sessions updates fail with conflicting or invalid data.
- **Test setup**: Create associations/sessions and populate them with conflicting or invalid data.
- **Test execution**: Attempt to update the associations/sessions with conflicting or invalid data and verify that the updates fail.
- **Test assertions**: Verify that the updates fail.
- **Test teardown**: Delete the associations/sessions.

## UPF Behavior Negative Test*

- **Test objective**: Test that the UPF behaves properly when external tools (free5gc/open5gs) are unavailable or unresponsive, and under extreme network conditions.
- **Test setup**: Set up the UPF with free5gc/open5gs and attempt to simulate unavailability or unresponsiveness of free5gc/open5gs and extreme network conditions.
- **Test execution**: Attempt to use the UPF under the simulated conditions
- **Test assertions**: Verify that the UPF behaves properly under the simulated conditions.
- **Test teardown**: Delete free5gc/open5gs and the UPF.

## Resize Function Test

- **Test objective**: Test that the `resize` function properly creates the eBPF map and all leftovers are cleaned.
- **Test setup**: Create an eBPF map and populate it with data.
- **Test execution**: Call the `resize` function
- **Test assertions**: Verify that the eBPF map is properly created and all leftovers are cleaned.
- **Test teardown**: Delete the eBPF map.

## `composeFarInfo` Test

- **Test objective**: Test that `composeFarInfo` produces expected output.
- **Test setup**: Create input data for `composeFarInfo`.
- **Test execution**: Call `composeFarInfo` with the input data.
- **Test assertions**: Verify that `composeFarInfo` produces expected output.

## Multiple Association Creation Test

- **Test objective**: Test that the UPF does not break when multiple associations are created.
- **Test setup**: Create multiple associations and populate them with data.
- **Test execution**: Attempt to create multiple associations
- **Test assertions**: Verify that the UPF does not break when multiple associations are created.
- **Test teardown**: Delete the associations.

## UEs Cannot See Each Other Directly Test?

- **Test objective**: Test that UEs cannot see each other directly.
- **Test setup**: Set up the UPF with free5gc/open5gs and multiple UEs.
- **Test execution**: Attempt to send data from UE to UE.
- **Test assertions**: Verify that UEs cannot see each other directly.
- **Test teardown**: Delete free5gc/open5gs and the UPF.

## Multiple UEs Reach Their Respective Destination Test

- **Test objective**: Test that with multiple UEs connected, all can reach their respective destination.
- **Test setup**: Set up the UPF with free5gc/open5gs and multiple UEs.
- **Test execution**: Attempt to allow multiple UEs to reach their respective destination
- **Test assertions**: Verify that with multiple UEs connected, all can reach their respective destination.
- **Test teardown**: Delete free5gc/open5gs and the UPF.

## Deployment Tests

- **Test objective**: Test that the UPF deploys properly.
- **Test setup**: Deploy the UPF.
- **Test execution**: Verify that the UPF is properly deployed.
- **Test assertions**: Verify that the UPF is properly deployed.
- **Test teardown**: Delete the UPF.

**Comment by ewdss** [comment]
I've added few comments into the Notion page here:
https://www.notion.so/Test-plan-for-edgecomllc-eupf-5G-User-Plane-Function-UPF-based-on-eBPF-github-com-aad61734d2d14d3fbcf877bda92bd377

And several more ideas are here:
- to implement 1-level structure inside the docs, i.e. place tests inside some top-level structure. Maby like this one:
  -- Functional tests: 
   --- eUPF and interfaces
   --- UE and e2e tests
   --- etc ...
- add stability test (XX hrs of permanent running), but don't pay more attention to the unfunctional tests. 
- add "cold reset test" - what should happend after unxpected restart of the eUPF?
