### ISSUE TITLE
Verify BGP-style internal routing in public cloud

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#335]
# Who What & Why 
I'm as a customer wants to deploy UPF solution with BGP connectivity in a public cloud to save CAPEX

# Additional info
## Acceptance criteria

1. 0-scenario works properly

# Definition of done
- [x] UPF + BGP adopter to be deployed on а public cloud
- [x] UPF + BGP deployed in YC
- [x] UPF + BGP deployed in GCP
- [x] Verify that it is possible to use BGP on K8s node

**Comment by mbaran0v** [comment]
YC:

1. no possibility to configure custom IP from Calico IP pool

error message, when pod is creating

```
Warning FailedCreatePodSandBox 3s kubelet Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "ff7daab013f4b01ba3a213cf3d08318a46efd2a0fb157fad335703 │
│ 731e5abefb": plugin type="calico" failed (add): ipAddrs is not compatible with configured IPAM: host-local
```

2. no possibility to configure BGP peering on Calico

```
root@cl181f4433gkuqc8vpoa-udaj:~# ./calicoctl node status
Calico process is running.

The BGP backend process (BIRD) is not running.
```

I talked to support and got this response:

> Уточнили информацию у коллег. Видим, что вы пытаетесь через crd calico самостоятельно определять диапазон ip для пода. Так в Managed сделать не получится, потому что мы выделяем диапазоны pod ip subnet'а на ноды и навешиваем статические маршруты, а на ноде calico agent раздает IPшники подам из podCIDR (как обычный bridge+local ipam CNI).

**Comment by mbaran0v** [comment]
GKE:

as well as in Yandex, the settings are identical. couldn't talk to customer service because it's not work without support plan
