### ISSUE TITLE
Use standart UPF and eUPF in simple slicing scenario

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#336]
# Who What & Why 
I'm as a MNO wants to deploy new slice in addition to my existing 5GC( including my own UPF) in order to provide client specific service via new slice.

# Additional info
## Acceptance criteria

1. 0-scenario works properly
2. Slicing scenario works properly

# Definition of done
- [x] Free5gc UPF used in slicing scenario for default slice
- [x] eUPF is used for specific slice
- [ ] Deployment configuration reviewed and merged in main branch

**Comment by PapaySail** [comment]
Open5GS UPF used for default slice, is OK?  @pirog-spb 
See #323

**Comment by pirog-spb** [comment]
That's ok
