### ISSUE TITLE
Create sample robotframework test for 0-scenario

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#337]
# Who What & Why 
I'm as a developer is able to chech that 5GC with eUPF works properly in order to verify changes in configuration or application.

# Additional info
## Acceptance criteria

# Definition of done
- [x] At least 0-scenario is configured in robot test
- [ ] Test run presented to team

**Comment by marknefedov** [comment]
[eupf.zip](https://github.com/edgecomllc/eupf/files/12014143/eupf.zip)



![Image](https://github.com/edgecomllc/eupf/assets/20001291/cdc252f3-d539-41f2-af90-a5e6a02f7768)

**Comment by marknefedov** [comment]
![Image](https://github.com/edgecomllc/eupf/assets/20001291/ab15f0cc-89df-4fe9-bd6d-d62e6b68711c)
