### ISSUE TITLE
Make slice scenario description

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#344]
# Who What & Why 
I'm as a slicing vendor can present slicing solution to customers in order to make brilliant presentation

# Additional info
## Acceptance criteria

# Definition of done
- [x] Slicing scenario demo described
- [x] Decide how to use online monitoring tools during demonstration
- [x] Visual aids added

**Comment by ewdss** [comment]
https://miro.com/app/board/uXjVPlO58Jc=/?moveToWidget=3458764559090406596&cot=14

**Comment by ewdss** [comment]
Demonstration tools:
 - simple one - tcpdump at UPF
 - nice one - graphana's dashboard that represent PPS/throughput on each UPF to show via which UPF traffic is routed.
