### ISSUE TITLE
Explore N9 interface specification

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#359]
# Who, What & Why
I'm as a devaloper understand clearly how N9 interface works.

# Additional info
## Acceptance criteria

# Definition of done
- [x] N9 interface explored
- [x] Link to spec included
- [x] Basic demo scenario documented

**Comment by marknefedov** [comment]
## N9 Interface Overview

The N9 Interface is a logical interface in the 5G network architecture, as described in the ETSI document [TS 123 501 V16.6.0](https://www.etsi.org/deliver/etsi_ts/123500_123599/123501/16.06.00_60/ts_123501v160600p.pdf). It looks like N9 Interface does not have its own specification and is controlled over the same N4 interface as the N3 interface. The primary difference between the N9 and N3 interfaces is the absence of GPT-U decapsulation and F-TEID preservation for routing PDU sessions to other UPFs, which may be located in different 5G cores.

### N9 Interface in ULCL Setups

The N9 Interface is particularly useful in User Plane Low Latency Communication (ULCL) setups between the I-UPF (Interworking UPF) and PSA-UPF (Packet Switched Access UPF). 

### Example Use Cases

One example of the N9 Interface's application can be found in the [5GAA document A-200150](https://5gaa.org/content/uploads/2021/03/5GAA_A-200150_MEC4AUTO_Task2_TR_MEC-for-Automotive-in-Multi-Operator-Scenarios.pdf), which discusses Multi-access Edge Computing (MEC) for automotive in multi-operator scenarios. In this context, the N9 Interface facilitates communication between UPFs in different 5G core networks, allowing for seamless connectivity and data exchange between vehicles and infrastructure in a multi-operator environment.

**Comment by ewdss** [comment]
Basic scenario description:
 - i-UPF should pass traffic from N3 to N9 to PSA-UPF. 
 - There is no ULCL, rules, routing or whatever on the i-UPF. Only N3-N9 interconnection. 
 - We should check that both i-UPF and PSA-UPF interacts with SMF corretly.
