### ISSUE TITLE
Update packet counter statistic representation

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#366]
I'm as a upf user can get separate N3 and N6 packet statistic in order to verify packet forwarding works ok.

Acceptance criteria:
- [ ] eUPF provides separate N3 and N6 counters via ebpf map
- [ ] N3 and N6 counters are visible through eUPF API
- [ ] API documentation updated

**Comment by pirog-spb** [comment]
In case of eUPF-on-a-stick it's not possible to distinguish N3 and N9 traffic...

**Comment by retroruiner** [comment]
- Added separate counters for N3 and N6 interfaces via eBPF map.
- [Pull request is made.](https://github.com/edgecomllc/eupf/pull/426)
