### ISSUE TITLE
Prepare standalone cloud UPF connection scheme

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#371]
Prepare UPF connection scheme for UPF deployed in cloud, connected to MNO's network and route N6 traffic to another service in cloud.

# Definition of done
- [x] Prepare general UPF connection scheme
- [x] Find out how to implement connection scheme on YC
- [x] Find out how to implement connection scheme on GCP

**Comment by mbaran0v** [comment]
https://miro.com/app/board/uXjVPlO58Jc=/?moveToWidget=3458764560658672251&cot=14
