### ISSUE TITLE
Deploy standalone eUPF in GCP with external connectivity

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#373]
# Definition of done
- [x] eUPF deployed in a GCP cloud
- [x] N4 interface is available for external SMF
- [x] N3 interface is available for external gNB
- [x] Update install documentation to describe eUPF in GCP scenario

**Comment by mbaran0v** [comment]
install documentation available here https://docs.google.com/document/d/1mUr9s5CPvaFe90rWs6A1tZmNEI3pG2K3Amy6n5ftuc4/edit
