### ISSUE TITLE
Prepare latency measurement tool for UERANSIM

### ISSUE THREAD

**Issue by ewdss** [edgecomllc/eupf#384]
Prepare several measurenent tools for UERANSIM:
- automatic continious e2e latancy management by blackbox_exporter as sidecar to ueransim
- manual per hop latency measurement by mtr as integrated tool in ueransim

It's unclear now how to route traffi from blackbox_exporter via ueransim tunnel

- Check `nr-bind` tool from UERANSIM

**Comment by ewdss** [comment]
Proposed blackbox-reporter tool works fine for e2e cases but can't measure latency between UE and eUPF. Additional solution or add-on should be found.

**Comment by mbaran0v** [comment]
https://github.com/edgecomllc/openverso-charts/pull/1/files
