### ISSUE TITLE
Prepare management UE interface prototype

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#399]
Explore 5GC, eUPF, eUPF API and competitors UI (Druid, pfSense, Nokia) and prepare management and monitoring UI prototype.

Acceptance criteria:

- [x] Explore eUPF API (https://github.com/edgecomllc/eupf/blob/main/docs/api.md)
- [x] Prepare several sketches(wireframes) for UI
- [x] Present to team

**Comment by pirog-spb** [comment]
@kade-ddnkv please add you UI sketches here and close the issue

**Comment by kade-ddnkv** [comment]
Presented to the team:
![8_1](https://github.com/edgecomllc/eupf/assets/88973774/6abe3bbe-055f-4a1f-bc1f-4ce751c89952)
![8_2](https://github.com/edgecomllc/eupf/assets/88973774/4abd502a-1cd9-4039-b2b8-d9788c1b23d7)
![8_3](https://github.com/edgecomllc/eupf/assets/88973774/24a8949a-182a-4832-bb02-2d95f6007477)
.
.
Other versions:
![overall](https://github.com/edgecomllc/eupf/assets/88973774/02eda0e1-c7ca-4e21-ab6b-4cdc21c73b3a)
![1](https://github.com/edgecomllc/eupf/assets/88973774/ba548698-4847-4bc6-8498-0c0cd25222c1)
![2](https://github.com/edgecomllc/eupf/assets/88973774/d06c2aff-8743-42b0-91bd-95faf9cc2881)
![3](https://github.com/edgecomllc/eupf/assets/88973774/73cb2ae1-0612-4d05-89c9-59be09723d76)
![4](https://github.com/edgecomllc/eupf/assets/88973774/66795e26-a13d-4785-aaa1-f8ae985b2606)
![6](https://github.com/edgecomllc/eupf/assets/88973774/cf357163-afbf-4082-b8ac-9f09a5f129c3)
![7_1](https://github.com/edgecomllc/eupf/assets/88973774/f3b4fe45-e042-4fcc-b50e-d1f4dd217340)
![7_2](https://github.com/edgecomllc/eupf/assets/88973774/e615ebce-fa42-49b2-aeef-6f7c97d87d35)
