### ISSUE TITLE
Fix BGP connection flapping

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#404]
BGP connection in eUPF's routing scheme with sidecar BIRD is constantly flapping every 5 sec. That causes removal of route to eUPF from host RT and connection freezes.

Investigare and find root case. Fix if possible.

**Comment by mbaran0v** [comment]
@pirog-spb could you help me remember command for enable debug logs in BIRD console ?

**Comment by pirog-spb** [comment]
BIRD logs how to:
- run birdcl: `sudo kubectl -n open5gs-demo-step3 exec -it -c bird eupf-58d9b8fbf6-ld22d -- birdcl`
- enable trace: `debug all all`
- turn on echo to console: `echo all`
- turn off echo: `echo off`

**Comment by pirog-spb** [comment]
According to tcpdump the BGP session is always dropped by BIRD in UPF



![Image](https://github.com/edgecomllc/eupf/assets/20152142/e5fded2c-b328-4cf8-a181-047d69cc9d93)

**Comment by pirog-spb** [comment]
Calico announced to UPF subnet **10.233.64.0/26** which may be treated by UPF as a strange(UPF IP is from announced subnet). Let's try to avoid sending this subnet to UPF.
