### ISSUE TITLE
Implement status UI for eUPF

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#406]
I'm as a eUPF user is able to see current system status in order to be sure that eupf up and running.

Acceptance criteria:

- [x] Status UI screen implemented
- [x] UI presented to team

**Comment by kade-ddnkv** [comment]
![screencap_ui](https://github.com/edgecomllc/eupf/assets/88973774/e7fe480a-3018-49cb-bb30-f7399d825885)
