### ISSUE TITLE
UE not able to connect to internet.

### ISSUE THREAD

**Issue by khushi798** [edgecomllc/eupf#410]
I have successfully established pdu session and below are the details of trying to ping google inside the ueransim container
![image](https://github.com/free5gc/free5gc-compose/assets/120015301/9f67dab3-9e37-4063-b282-5454a55385e1)

![image](https://github.com/free5gc/free5gc-compose/assets/120015301/ff50602f-70c0-41d4-ae6a-39b1ebef9d33)
Here i am pinging google.com from uesimtun1 interface  
below i am trying the same with uesimtun0 interface

![image](https://github.com/free5gc/free5gc-compose/assets/120015301/0c765bb6-3de8-4457-a416-920b4a367a70)

**Comment by pirog-spb** [comment]
Hi @khushi798 

Could you please clarify what kind of deployment you used?

**Comment by khushi798** [comment]
> Hi @khushi798
> 
> Could you please clarify what kind of deployment you used?

I used docker compose method. In the docker compose everything is fine , all the containers are working and I've tested the eupf also. There are 2 containers running for eupf one is for swagger and the other is for Core manager. 
![image_2023-09-14_13-39-02](https://github.com/edgecomllc/eupf/assets/120015301/db52793a-2c86-4584-9a92-f5483181c897)
![image_2023-09-14_13-43-31](https://github.com/edgecomllc/eupf/assets/120015301/6f762f02-89f0-4639-8bc5-a8e3b9d6d99c)

I've successfully established the pdu session but when I ping this command
```shell
ping -I uesimtun0 google.com
``` 
Packets are not received in the amf container.there was 100% packet loss.
I want the solution as for why the amf is not responding to the request of ping command.
([AMF.txt](https://github.com/edgecomllc/eupf/files/12606412/AMF.txt) logs of AMF )

**Comment by khushi798** [comment]
> Hi @khushi798
> 
> Could you please clarify what kind of deployment you used?

I have been using the Docker Compose method for deployment. Everything seems to be functioning correctly in the Docker Compose setup, as all the containers are up and running, and I've successfully tested the EUPF .

Specifically, there are two containers running for EUPF: one for Swagger and the other for Core Manager. Here are some screenshots for reference:

![EUPF Swagger Container](https://github.com/edgecomllc/eupf/assets/120015301/db52793a-2c86-4584-9a92-f5483181c897)
my eupf is sending proper heartbeats to smf
![EUPF Core Manager Container](https://github.com/edgecomllc/eupf/assets/120015301/6f762f02-89f0-4639-8bc5-a8e3b9d6d99c)

The issue arises when I try to establish a PDU  session and execute the following ping command within the container:

```shell
ping -I uesimtun0 google.com
```

Unfortunately, I'm experiencing 100% packet loss, and the AMF  container does not respond to the ping request.

I have attached the logs of the AMF for your reference: [AMF.txt](https://github.com/edgecomllc/eupf/files/12606412/AMF.txt).

I would greatly appreciate any assistance or insights into why the AMF is not responding to the ping command request. Thank you!

**Comment by pirog-spb** [comment]
Try this brief debug algorithm:

1. All containers are up and running
2. UE is registered (check UE logs or UE status via cli)
3. PDU session is established (check UE logs, UE has IP address assigned)
4. Check packets in eUPF: tcpdump on veth pair side on host (`ip l sh` in eupf container, that use corresponging interface on host)
5.  Check packets in NAT container: tcpdump in container on corresponfing interface

**Comment by PapaySail** [comment]
> there is no response to the ping request.

If you can ping local node ip addrs, like addr of docker0 interface, throught uesimtun0, then look forward.
If you have installed [IP Masquerade Agent](https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent/), it's point of inconsistency. Check it at the node by command `sudo iptables -t nat -L IP-MASQ-AGENT`. If output will be like these:
```prolog
sergo@edgecom:~$ sudo iptables -t nat -L IP-MASQ-AGENT
Chain IP-MASQ-AGENT (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             169.254.0.0/16       /* ip-masq-agent: local traffic is not subject to MASQUERADE */
RETURN     all  --  anywhere             10.0.0.0/8           /* ip-masq-agent: local traffic is not subject to MASQUERADE */
RETURN     all  --  anywhere             172.16.0.0/12        /* ip-masq-agent: local traffic is not subject to MASQUERADE */
RETURN     all  --  anywhere             192.168.0.0/16       /* ip-masq-agent: local traffic is not subject to MASQUERADE */
MASQUERADE  all  --  anywhere             anywhere             /* ip-masq-agent: outbound traffic is subject to MASQUERADE (must be last in chain) */
```
then disable it and clear the rule:
```prolog
sudo kubectl delete -f https://raw.githubusercontent.com/kubernetes-sigs/ip-masq-agent/master/ip-masq-agent.yaml
sudo iptables -t nat -D IP-MASQ-AGENT -m comment --comment "ip-masq-agent: outbound traffic is subject to MASQUERADE (must be last in chain)" -j MASQUERADE
``` 
Check the result at the UE container. (No need to restart anything.)

**Comment by pirog-spb** [comment]
Yet another hint to solve a problem: check ip routes in nat container (`ip r sh`). 
It was noticed that sometimes route to UE subnet isn't applied. If you have ping replies in nat container, but no replies in UE, this could be the root cause.

**Comment by khushi798** [comment]
Hi !
@pirog-spb  @PapaySail 
Thank you for your help and suggestions as well  .  As for now my UE is connected to the  internet and working happily .
