### ISSUE TITLE
eUPF deployment failed in kubernetes along with free5gc 

### ISSUE THREAD

**Issue by Satyam-git-hub** [edgecomllc/eupf#411]
Hello,
I was trying to deploy eupf along with free5gc using minikube with multus and calico cni but the pods were unable to initialize
and were  sysctlforbidden error 

![image](https://github.com/edgecomllc/eupf/assets/67541381/6ae0a272-913c-4d3d-bd46-cf2e5ecbe50a)
eupf pod describe.txt is [here](https://github.com/edgecomllc/eupf/files/12607494/desc.txt)

Also 
in free5gc amf,smf pods were not initializing
![image](https://github.com/edgecomllc/eupf/assets/67541381/81fc5fb1-7fc6-4a78-a738-98a124b09334)

**Comment by PapaySail** [comment]
Hello!
> sysctlforbidden error

I guess you have to follow the instructions [Enabling Unsafe Sysctls](https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#enabling-unsafe-sysctls). For Minikube extra-config flag might be like this:
`minikube start --extra-config="kubelet.allowed-unsafe-sysctls=net.ipv4.ip_forward,net.ipv6.conf.all.forwarding"`



> in free5gc amf,smf pods were not initializing

Look at the pod description, section Events - there you will find the cause.

**Comment by Satyam-git-hub** [comment]
hi @PapaySail  
Thank you for your reply  
![image](https://github.com/edgecomllc/eupf/assets/67541381/804fb728-2a95-4015-996d-11772a9fa015)
I tried with the method u said but still eupf pod is stuck at container creating stage
[edgecomllc-eupf.log](https://github.com/edgecomllc/eupf/files/12618134/edgecomllc-eupf.log)

**Comment by PapaySail** [comment]
> eupf pod is stuck at container creating stage
> failed (add): failed to lookup master "ens3": Link not found

Configuration wrote assuming the physical network interface on Kubernetes node named `ens3`.
But you have another name of physical network interface, for example `eth0`. So, change it inside helmchart values files:
```ruby
sed -i 's/"master":.*/"master": "eth0",/'  docs/examples/free5gc/eupf*.yaml
sed -i 's/masterIf:.*/masterIf: eth0/'  docs/examples/free5gc/free5gc-single.yaml
```
Update helmchart release (`helm upgrade --install ...`).
Your pod should start successfully.
Thanks!
