### ISSUE TITLE
Prepare UE emulation projects comparison

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#414]
eUPF has been already integrated with UERANSIM project. srsRAN project is under reasearch at the moment. In order to share our experience to community procs and cons, pitfalls and advantages of both RAN emulation projects have to be documanted.

- [ ] Comparison table prepared and documented
- [ ] Usage experience are breifly documented

**Comment by linouxis9** [comment]
You might want to check https://github.com/HewlettPackard/PacketRusher as well :-)
