### ISSUE TITLE
Performance testbed research

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#429]
I'm, as a developer, want to verify eUPF performance in order to provide high performance solution for more then 5Gbps per core.

Current test environment(UERANSIM + iperf) provides low performance(400Mbps).

Acceptance criteria:

- [x] Consider dedicated servers case only
- [x] Proc and cons are published and presented to team

**Comment by mbaran0v** [comment]
provider | hardware | price
-- | -- | --
reg.ru | 2 × Intel Xeon E5620 8 ГБ DDR3 | 7000 month
selectel.ru | Intel Xeon L5630 2.13 ГГц, 8 ядер 24 ГБ DDR3 | 4100 month (320 day)
vdsina.ru | 8 core 30 ГБ Память | 14460 month (482 day)
1dedic.ru | Core i7 9700K 8 ядер 3.6-4.9 ГГц 16Гб | 5239 month
timeweb.com | Intel Core i9-9900K 8 ядер • 3.6-5.0 ГГц • 16 потоков 32 Гб DDR4 | 11640 month
vultr.com | Intel E-2288G 8 cores / 16 threads @ 3.7GHz 128 GB Memory | $350/month $0.521/hour
hetzner.de | Intel® Core™ i5-13500 14 core | € 46.41
oneprovider.com | Core i7-6700K 4 GHz | 42.63
hostkey.com | BM 2xE5-2680v2/128/2x960 | € 105


dedicated server is interesting, but I don't see any reason to use it
