### ISSUE TITLE
Update grafana slicing dashboard

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#430]
I'm, as a slicing promoter, show slicing demo using grafana dashboards where monitoring parameters are shown per slice separatly.

Acceptance criteria:

- [x] Every monitoring parameter is shown per slice if possible
- [x] Dynamical panel per slice supported
- [ ] Updated dashboard reviewed
- [ ] Source code of dashboard merged in repo
- [ ] Dashboard deployed in K8s demo stand

**Comment by PapaySail** [comment]
Row options
>    Title
    S-NSSAI $snssai
    Repeat for
    snssai

Panel SMF query A : `ues_active and on(job) fivegs_smffunction_sm_sessionnbr{snssai="$snssai"}`
filter for SMF related to $snssai only
refer to https://stackoverflow.com/questions/63660751/nesting-query-in-promql#63667762
> Selecting all instances with a particular label can be done with the and operator, which will return the left hand side if the labels on the right hand side has matching labels.

dashboard looks like:
![image](https://github.com/edgecomllc/eupf/assets/125686203/70cf27f5-3621-4637-8e33-3400a5e10f96)

Update open5gs_sessions.json  https://github.com/edgecomllc/eupf/pull/442
