### ISSUE TITLE
Prepare multi gNB deployment

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#431]
I'm, as a eUPF developer, can deploy several gNB to open5gs core and eUPF in order to run several iperf test each via separate gNB (and UEARANSIM).

Acceptance criteria:

- [x] Multi gNB deployment prepared
- [x] Multi iperf test performed
- [x] Results are presented to team

**Comment by mbaran0v** [comment]
linked PR https://github.com/edgecomllc/open5gs-compose/pull/1
