### ISSUE TITLE
Multi gNB performace test

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#432]
I'm, as a eUPF developer, scale iperf performance test using multi gNB deployment in order to verify eUPF performance (at least 1Gbps).

Acceptance criteria:

- [x] Scaled iperf test on TEST performed
- [x] Results presented to team

**Comment by mbaran0v** [comment]
test environment:

iperf Linux VM (2CPU, 2 Gb RAM)
core Linux VM (8CPU, 8 Gb RAM)

**Comment by mbaran0v** [comment]
## test 1 (server - server)

here, we checks ideal network throughput btw VMs (iperf and core)
￼
<img width="904" alt="Pasted Graphic" src="https://github.com/edgecomllc/eupf/assets/2111147/d51a4f10-26a3-4be7-a0e7-ab8511c93cf0">

```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-60.00  sec  40.2 GBytes  5.75 Gbits/sec  2281             sender
[  5]   0.00-60.05  sec  40.2 GBytes  5.75 Gbits/sec                  receiver

```

**Comment by mbaran0v** [comment]
## test 2 (one ueransim container - iperf)

here, we check network throughput btw ueransim container and core VM

￼
<img width="945" alt="Pasted Graphic 4" src="https://github.com/edgecomllc/eupf/assets/2111147/83d5e6a3-1a64-4ff6-bada-da099d29bf76">


```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-60.00  sec  39.2 GBytes  5.61 Gbits/sec  5521             sender
[  5]   0.00-60.04  sec  39.2 GBytes  5.61 Gbits/sec                  receiver

```

**Comment by mbaran0v** [comment]
## test 3 (one ueransim container - upf - iperf)

here, we check network throughput btw ueransim container and core VM via open5gs UPF

￼
<img width="1034" alt="Pasted Graphic 1" src="https://github.com/edgecomllc/eupf/assets/2111147/5fda0b96-6bcc-4f7b-81d4-cd4f180a2665">


```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-60.00  sec  2.57 GBytes   368 Mbits/sec  4123             sender
[  5]   0.00-60.04  sec  2.57 GBytes   367 Mbits/sec                  receiver

```

**Comment by mbaran0v** [comment]
## test 4 (one ueransim container - eupf - iperf)

here, we check network throughput btw ueransim container and core VM via eUPF

￼
<img width="1011" alt="Pasted Graphic 2" src="https://github.com/edgecomllc/eupf/assets/2111147/d42c03ff-e1a0-4009-aa25-f74f51dff72d">


```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-109.95 sec  4.67 GBytes   365 Mbits/sec  7201             sender
[  5]   0.00-109.95 sec  0.00 Bytes  0.00 bits/sec                  receiver

```
**same results for scheme without NAT**

**Comment by mbaran0v** [comment]
## test 5 (multiple ueransim containers, one gNB - eupf - iperf)

here, we check network throughput btw 2 ueransim containers and core VM via eUPF with 1 gNB

￼
<img width="998" alt="Pasted Graphic 3" src="https://github.com/edgecomllc/eupf/assets/2111147/ae1fb253-9276-4557-820b-a03d9be806b3">


```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-60.00  sec  1.23 GBytes   176 Mbits/sec  3536             sender
[  5]   0.00-60.04  sec  1.23 GBytes   176 Mbits/sec                  receiver

```
and

```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-60.00  sec  1.25 GBytes   179 Mbits/sec  3819             sender
[  5]   0.00-60.04  sec  1.25 GBytes   178 Mbits/sec                  receiver

```

**Comment by mbaran0v** [comment]
## test 6 (multiple ueransim containers, 2 gNB - eupf - iperf)

here, we check network throughput btw 2 ueransim containers and core VM via eUPF with 2 gNB

￼
<img width="1015" alt="Pasted Graphic 5" src="https://github.com/edgecomllc/eupf/assets/2111147/1bd0ccfc-87c2-4e17-b7fc-8594cad432a5">


```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-60.00  sec  1.66 GBytes   238 Mbits/sec  1964             sender
[  5]   0.00-60.04  sec  1.66 GBytes   237 Mbits/sec                  receiver

```
and

```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-60.00  sec  1.68 GBytes   241 Mbits/sec  2069             sender
[  5]   0.00-60.04  sec  1.68 GBytes   240 Mbits/sec                  receiver

```

**Comment by mbaran0v** [comment]
## test 7 (multiple ueransim containers, multiple gNB - eupf - iperf)

here, we check network throughput btw 6 ueransim containers and core VM via eUPF with 6 gNB

￼
<img width="999" alt="Pasted Graphic 6" src="https://github.com/edgecomllc/eupf/assets/2111147/a6aa3901-b4aa-461a-adeb-5eab5205e9a0">


```
[  5]   0.00-30.05  sec   431 MBytes   120 Mbits/sec                  receiver
[  5]   0.00-30.05  sec   435 MBytes   122 Mbits/sec                  receiver
[  5]   0.00-30.05  sec   434 MBytes   121 Mbits/sec                  receiver
[  5]   0.00-30.04  sec   438 MBytes   122 Mbits/sec                  receiver
[  5]   0.00-30.05  sec   438 MBytes   122 Mbits/sec                  receiver
[  5]   0.00-30.05  sec   437 MBytes   122 Mbits/sec                  receiver
```
