### ISSUE TITLE
pcap file request

### ISSUE THREAD

**Issue by Satyam-git-hub** [edgecomllc/eupf#445]
Can you pls share a pcap file in the repo and also pls show which bpf programs are attached to xdp

**Comment by PapaySail** [comment]
> which bpf programs are attached to xdp

Answered at https://github.com/edgecomllc/eupf/issues/443#issuecomment-1765887693
>> upf_ip_entrypoint  is the only ebpf program that is attached to network interfaces at the moment. The rest programs are just stubs. You may ignore them without any doubts.



> share a pcap file

As shown in issue https://github.com/edgecomllc/eupf/issues/443#issuecomment-1768361598 , you can see packets capture.
So, I believe the request is irrelevant.
