### ISSUE TITLE
eUPF in ULCL scenario don't resolve ARP for ancor UPFs

### ISSUE THREAD

**Issue by PapaySail** [edgecomllc/eupf#465]
As described in https://github.com/edgecomllc/eupf/issues/456#issuecomment-1775708888 overcome approach needed for traffic to go throught eUPF to next UPF in ULCL scenario with N9 interfaces.
>  we need to open eupf shell and start pinging both upf1 and upf2

**Comment by pirog-spb** [comment]
My proposed solution is to add GTP Path management feature. eUPF have to send GTP Echo Request to every known GTP peer.

**Comment by pirog-spb** [comment]
Simple GTP Path management option implemented:

- Every peer should be configured to be monitored (see `gtp_peer` config option)
- eUPF for each configured peer every `echo_interval` seconds send GTP Echo request and wait for an response
- If no response - drop a line in log file
