### ISSUE TITLE
UPF UE IP address allocation

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#478]
I'm as a UPF vendor can configure UPF to allocate IP addressed for PDU sessions locally.

Acceptance criteria:

- [x] Explore how it works ([5.21.3 UE IP address/prefix allocation in the UP function](https://www.etsi.org/deliver/etsi_ts/129200_129299/129244/16.04.00_60/ts_129244v160400p.pdf))
- [x] Implement IP pool
- [x] Set UEIP flag during PFCP Association Request/Respose
- [x] Use CHV4 flag to trigger IP address allocation
- [x] Write unit/acceptance test to verify this function
- [x] Update README: functional description + 3gpp compatibility
- [x] Add issues to free5gc/open5gs... to support `UEIP`
- [ ] Present to team

**Comment by arxxm** [comment]
free5gc issue: https://github.com/free5gc/free5gc/issues/509
open5gc issue: https://github.com/open5gs/open5gs/issues/2741
