### ISSUE TITLE
Verify github documentation

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#510]
Acceptance criteria:
- [ ] Deployment configs
- [x] Add docker-compose open5gs link
- [x] Add docker-compose free5gc ulcl link
- [x] Relative repos links and access rigths
- [x] Check comments in code
- [ ] Check absolete files in repo

**Comment by PapaySail** [comment]
- ❓ "Add docker-compose free5gc ulcl link" - where from?  @pirog-spb 
- Make repository https://github.com/edgecomllc/open5gs-compose Public, please @pirog-spb 
- 🤷‍♂️ " Check obsolete files in repo" - which one? : needed competent helper

**Comment by pirog-spb** [comment]
> ❓ "Add docker-compose free5gc ulcl link" - where from? @pirog-spb

See https://github.com/edgecomllc/free5gc-compose/tree/ulcl-n9upf-experimetns

> Make repository https://github.com/edgecomllc/open5gs-compose Public, please @pirog-spb

Done
