### ISSUE TITLE
Can't build EUPF

### ISSUE THREAD

**Issue by mandrade1stf** [edgecomllc/eupf#526]
**Describe the bug**

I can't build EUPF 

**To Reproduce**

I use steps to build, but:

```
root@open5gs-iperf04-6589c5768d-8szmr:/eupf# go build -v -o bin/eupf ./cmd/
cmd/api/rest/handler.go:8:2: no required module provides package github.com/edgecomllc/eupf/cmd/docs; to add it:
        go get github.com/edgecomllc/eupf/cmd/docs
root@open5gs-iperf04-6589c5768d-8szmr:/eupf# go get github.com/edgecomllc/eupf/cmd/docs
go: github.com/edgecomllc/eupf/cmd/docs: no matching versions for query "upgrade"
root@open5gs-iperf04-6589c5768d-8szmr:/eupf#
```

**Expected behavior**

**Screenshots**
![image](https://github.com/edgecomllc/eupf/assets/108490342/1d996a38-2e1e-4583-92d6-5c2b012bc32e)

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [ubuntu]
 - 5GC kind and version [ open5gs]
 - UPF version [last]

**Additional context**

**Comment by pirog-spb** [comment]
Hi @mandrade1stf 

Please verify that previous step (`go generate -v ./cmd/...`) was successfully finished. Package `eupf/cmd/docs` is genereted during that step.

If you have swag utility error there, check that swag was installed and path to swag binary is in $PATH env variable.

--BR Alex

**Comment by mandrade1stf** [comment]
I recive this error:
`cmd/main.go:25: running "swag": exec: "swag": executable file not found in $PATH`

I resolve with this command:

`export PATH=$(go env GOPATH)/bin:$PATH`

Thanks

**Comment by pirog-spb** [comment]
@mandrade1stf I've added hint to README concerning this issue.
