### ISSUE TITLE
Deployment commands issue

### ISSUE THREAD

**Issue by piktaka** [edgecomllc/eupf#557]
In the main page you provided commands to deploy the EUPF with docker the 2 commands will not work , because of a space after the backslash here : "-v /sys/fs/bpf:/sys/fs/bpf \ " (second line) , the same line in the second deployment command. Not an important issue but need to be fixed.

**Comment by pirog-spb** [comment]
Hi @piktaka 

Thank you for feedback!
Could you please clarify which deployment command you are talking about? From README page?

-- BR, Alex

**Comment by piktaka** [comment]
Hi @pirog-spb  , the section is the quick-start-guide which demonstrate 2 type of commands to deploy the eupf using docker  : "https://github.com/edgecomllc/eupf?tab=readme-ov-file#quick-start-guide" .
In the 2 commands you will find the issue.
Greetings.

**Comment by pirog-spb** [comment]
Fixed in #559
