### ISSUE TITLE
About XDP mode optional value in Configuration.md

### ISSUE THREAD

**Issue by s5uishida** [edgecomllc/eupf#574]
Hi,

Isn't the option value `offloaded` for XDP mode in `Configuration.md` supposed to be `offload`?

**Comment by pespin** [comment]
@s5uishida I just happened to run into this issue as well and submitted a PR here: https://github.com/edgecomllc/eupf/pull/575

**Comment by pirog-spb** [comment]
Hi guys,

FYI PR #575 has been approved and merged
